Vagrant.configure("2") do |config|
    config.vm.box = "uwbbi/bionic-arm64"
    config.vm.box_download_insecure = true
    config.vm.provider "vmware_desktop" do |v|
        v.ssh_info_public = true
        v.gui = true
        v.linked_clone = false
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
    end
    machine.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get update -y
      sudo apt-get install -y python3 python3-pip python3-psycopg2 python3-django
    SHELL
    config.vm.provision "file", source: "testfile", destination: "testfile"
end
